version : '2'
services:
  jenkins:
    container_name: jenkins-udd
    image: jenkins:2.3
    volumes:
      - jenkins-data:/var/jenkins_home
    environment:
      - JENKINS_OPTS=--prefix=/jenkins
  sonarqube-database:
    container_name: sonar-database-udd
    image: postgres:9.4
    volumes:
      - sonarqube-database-data:/var/lib/postgresql/data
    environment:
      - POSTGRESQL_DB=sonar
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
  sonar:
    container_name: sonar-udd
    image : sonarqube:5.5
    volumes:
      - sonarqube-data-data:/opt/sonarqube/data
      - sonarqube-extensions-data:/opt/sonarqube/extensions
    links:
      - sonarqube-database
    environment:
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonarqube-database:5432/sonar
    entrypoint:
      - ./bin/run.sh
      - -Dsonar.log.level=INFO
      - -Dsonar.web.context=/sonar
  nginx:
    container_name: nginx-udd
    build: nginx/.
    ports:
      - "80:80"
    links:
      - sonar
      - jenkins
      - nexus
    environment:
      - NGINX_PORT=80
      - NGINX_HOST=localhost
    command: >
      /bin/bash -c "
      envsubst < /var/tmp/udd.conf > /etc/nginx/conf.d/udd.conf
      && nginx -g 'daemon off;'"
  nexus:
    container_name: nexus-udd
    image : sonatype/nexus
    environment:
      - CONTEXT_PATH=/nexus

volumes:
  jenkins-data:
  sonarqube-database-data:
  sonarqube-data-data:
  sonarqube-extensions-data:
