FROM nginx

COPY WelcomePage /usr/share/nginx/welcome

#CMD rm /etc/nginx/conf.d/default.conf
COPY configuration/sites-available/udd  /etc/nginx/conf.d



#COPY configuration/sites-available/udd /etc/nginx/sites-available/udd



